/**
 * The museum's model, as this repository holds it. Generated by `mw init`;
 * the universal collections only.
 *
 *   src/model/records/<id>.json     one per image or document
 *   src/model/entities/<slug>.json  people, places, ...: each anchored
 *   src/model/questions/<id>.json   bounded open questions
 *   src/model/evidence.json         claims linked to records
 *   src/model/both-stand/<id>.json  disagreements standing: two claims, both cited
 *   src/model/links.json            quiet doors between records, each basis cited
 *   src/data/corrections/<id>.json  the queue: corrections, and everything the machine proposes
 *   meta/sequences.json             IDs claimed, by input hash
 *   meta/tombstones.json            IDs retired, never reissued
 */
import { readFolder, readJson } from "./files.ts";

export type Passage = { id: string; text: string };

/** Where a record (or a proposal) came from, when `mw` wrote it. */
export type Source = {
  url?: string;
  file?: string;
  file_url?: string;
  page?: number;
  model?: string;
  extracted_at?: string;
  input_hash?: string;
  tool?: string;
};

export type RecordNote = { date: string; note: string };

export type MuseumRecord = {
  id: string;
  kind: "image" | "document" | "object" | "log";
  title: string;
  /** Verbatim, or empty. Never invented. */
  caption?: string;
  credit?: string;
  alt?: string;
  /** The record (a page, a PDF) it was found in. */
  found_in?: string;
  position?: number;
  follows?: string;
  passages?: Passage[];
  rights_holder?: string;
  held: boolean;
  status: "verified" | "unverified" | "not-held";
  media?: string[];
  source?: Source;
  capture_provenance?: Record<string, string>;
  notes?: RecordNote[];
};

export const ENTITY_KINDS = ["person", "family", "place", "organization", "event"] as const;
export type EntityKind = (typeof ENTITY_KINDS)[number];

export type Entity = {
  id: string;
  slug: string;
  kind: EntityKind;
  label: string;
  aliases?: { name: string; sources?: string[] }[];
  anchors?: string[];
  notes?: RecordNote[];
};

export type OpenQuestion = {
  id: string;
  title: string;
  what_we_know: string;
  what_we_dont: string;
  what_might_answer_it: string;
  evidence_needed: string;
  last_known_source?: string[];
  entities?: string[];
  status: "open" | "answered";
  evidence?: string[];
  curator: string;
  date: string;
  /** The question or gap proposal it was kept from, if any. */
  from_proposal?: string;
};

export type EvidenceLink = {
  id: string;
  claim: { span: string; quote: string };
  record: string;
  type: "supports" | "contradicts" | "qualifies";
  note?: string;
  curator: string;
  date: string;
};

/**
 * What may arrive in the queue (Proposal Kinds Spec v1). The machine
 * proposes, the human disposes: no kind writes anything beyond the queue.
 *   text           a correction: the span as it should read, whole
 *   name           a name the span spells
 *   contradiction  two claims in conflict, each cited
 *   question       something missing, raised by a record
 *   gap            a hole in a provenance chain, its two ends cited
 *   duplicate      two records that may be one thing twice
 *   link           a connection between two records, its basis cited on both
 */
export const PROPOSAL_KINDS = ["text", "name", "contradiction", "question", "gap", "duplicate", "link"] as const;
export type ProposalKind = (typeof PROPOSAL_KINDS)[number];

/** Words a span holds, quoted: the evidence every proposal stands on. */
export type Cite = { span: string; quote: string };

export const LINK_BASES = ["shared name", "shared place", "shared date"] as const;

export type Correction = {
  id: string;
  kind?: ProposalKind;
  /** The span it concerns: "<record>#<passage>" or "plate:<record>" (for the newer kinds, its first citation's). */
  target: string;
  /** Every proposal of the newer kinds cites its spans; no citation, no acceptance. */
  cites?: Cite[];
  /** question: what is missing, and the record that raises it. */
  question?: { text: string; record: string };
  /** gap: the record, and what is missing between the two cited ends of its chain. */
  gap?: { record: string; missing: string };
  /** duplicate, link: the two records. */
  pair?: { a: string; b: string };
  /** link: what the two records share. */
  basis?: (typeof LINK_BASES)[number];
  proposed_text: string;
  entity_kind?: EntityKind;
  reason: string;
  proposed_by: string;
  date: string;
  status: "proposed" | "accepted" | "applied" | "rejected" | "held";
  decided_by?: string;
  decided_on?: string;
  curator_note?: string;
  /** Once applied: the words the span read before. */
  original_text?: string;
  source?: Source;
};

/** A disagreement standing: both claims cited, neither resolved by the museum. */
export type BothStand = {
  id: string;
  title: string;
  claim_a: Cite;
  claim_b: Cite;
  status: "standing" | "settled";
  /** Settled only with a note saying how (the book, a record found). */
  settled_note?: string;
  opened_by: string;
  opened_on: string;
  /** The contradiction proposal it was kept from, if any. */
  from_proposal?: string;
};

/** A quiet door between two records ("Also"), its basis cited on both sides. */
export type RecordLink = {
  id: string;
  from: string;
  to: string;
  basis: (typeof LINK_BASES)[number];
  cites: Cite[];
  curator: string;
  date: string;
  from_proposal?: string;
};

export type Sequence = { prefix: string; width: number; next: number };
export type Sequences = { record: Sequence; correction: Sequence; claims: Record<string, string> };
export type Tombstone = { id: string; date: string; reason: string };

export type Museum = {
  slug: string;
  title: string;
  rights_holder: string;
  status: string;
  text_freeze: boolean;
  schema_version: number;
};

export type Model = ReturnType<typeof loadModel>;

/** The whole model, read from the repository at `base`, with each file's name kept for the file-name checks. */
export function loadModel(base: URL) {
  const files = {
    records: readFolder(base, "src/model/records") as { file: string; data: MuseumRecord }[],
    entities: readFolder(base, "src/model/entities") as { file: string; data: Entity }[],
    questions: readFolder(base, "src/model/questions") as { file: string; data: OpenQuestion }[],
    corrections: readFolder(base, "src/data/corrections") as { file: string; data: Correction }[],
    bothStand: readFolder(base, "src/model/both-stand") as { file: string; data: BothStand }[],
  };
  return {
    museum: readJson<Museum | null>(base, "src/model/museum.json", null),
    files,
    records: files.records.map((f) => f.data),
    entities: files.entities.map((f) => f.data),
    questions: files.questions.map((f) => f.data),
    corrections: files.corrections.map((f) => f.data),
    evidence: readJson<EvidenceLink[]>(base, "src/model/evidence.json", []),
    bothStand: files.bothStand.map((f) => f.data),
    links: readJson<RecordLink[]>(base, "src/model/links.json", []),
    sequences: readJson<Sequences | null>(base, "meta/sequences.json", null),
    tombstones: readJson<Tombstone[] | null>(base, "meta/tombstones.json", null),
  };
}

/** Every span's words, by key: each passage ("r-0001#p3") and each record's caption ("plate:r-0002"). */
export function spans(records: MuseumRecord[]): Map<string, string> {
  const out = new Map<string, string>();
  for (const r of records) {
    for (const p of r.passages ?? []) out.set(`${r.id}#${p.id}`, p.text);
    if (r.kind === "image" || r.caption) out.set(`plate:${r.id}`, r.caption ?? "");
  }
  return out;
}

/** The record a span belongs to. */
export const spanRecord = (key: string) =>
  key.startsWith("plate:") ? key.slice(6) : key.split("#")[0];

/** All of a record's own words: title, caption, credit, alt text and passages. */
export const recordText = (r: MuseumRecord) =>
  [r.title, r.caption ?? "", r.credit ?? "", r.alt ?? "", ...(r.passages ?? []).map((p) => p.text)].join(
    "\n",
  );
